/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author labtecweb10
 */
public class SumaNumeros extends javax.swing.JFrame {

    /**
     * Creates new form SumaNumeros
     */
    public SumaNumeros() {
        initComponents();
        this.setSize(553, 302);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setWallpaper(wallpaper);
    }

    public static void setWallpaper(JLabel wallpaper) {
        ImageIcon imagen = new ImageIcon("./src/image/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(wallpaper.getWidth(),
                wallpaper.getHeight(), Image.SCALE_DEFAULT));
        wallpaper.setIcon(icono);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUno = new javax.swing.JTextField();
        txtDos = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUno.setBackground(new java.awt.Color(153, 204, 255));
        txtUno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtUno.setForeground(new java.awt.Color(255, 255, 255));
        txtUno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 210, 25));

        txtDos.setBackground(new java.awt.Color(153, 204, 255));
        txtDos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDos.setForeground(new java.awt.Color(255, 255, 255));
        txtDos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 210, 25));

        button.setText("comprobar");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));

        result.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 440, 52));

        jLabel2.setText("Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnoActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        
        String num1 = txtDos.getText().trim();
        String num2 = txtUno.getText().trim();
        
        int numUno;
        int numDos;
        boolean band = true;
        
        if (num1.equals("")) {
            txtDos.setBackground(Color.red);
            band = false;
        } else {
            txtDos.setBackground(new Color(153,204,255));
        }
        
        if (num2.equals("")) {
            txtUno.setBackground(Color.red);
            band = false;
        } else {
            txtDos.setBackground(new Color(153,204,255));            
        }
        
        if (band) {
            try {
                numUno = Integer.parseInt(num1);
                numDos = Integer.parseInt(num2);
                
                if (numUno % numDos == 0) {
                    result.setText("Los numeros son divisibles entre ellos");
                } else {
                    result.setText("Los numeros no son divisibles entre ellos");
                    
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Solo debe ingresar numeros");
                
            }
        }
        

    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumaNumeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel result;
    private javax.swing.JTextField txtDos;
    private javax.swing.JTextField txtUno;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
